import Head from 'next/head';
import dynamic from 'next/dynamic';
import { GlobalStyle } from '@/styles/GlobalStyles';
import { ThemeProvider } from 'styled-components';
import { theme } from '../../styles/theme';

import Background from '../background/background';

const Navbar = dynamic(() => import('../navbar/navbar'), { ssr: false });

interface LayoutProps {
  children: React.ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>JayCode</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/profile.jpeg" />
      </Head>
      <GlobalStyle />
      <Background />
      <Navbar />
      {children}
    </ThemeProvider>
  );
}
